version: '3'
services:
  db:
    image: mysql:8.0.31
    container_name: db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ticketsApp
  api:
    image: app:v1
    container_name: flaskApp
    ports:
      - '5000:5000'
    networks:
      - ticketsApp
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
networks:
  ticketsApp:
volumes:
  dbdata: