apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: app
spec:
  selector:
    app: mysql
  clusterIP: None   # Headless Service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
