name: asdf

on: [push]

env:
  REGISTRY: docker.io
  IMAGE_NAME: abir10101/tickets-app

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Depoloy with kubernates
        run: |
          kubectl apply -k kubernates/
