name: Linting & Testing

on: [push]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Stop default mysql
    #   run: sudo service mysql stop
    # - name: Mysql
    #   uses: mirromutth/mysql-action@v1.1
    #   with:
    #     mysql version: '5.7'
    #     mysql database: 'myapp'
    #     mysql root password: 'admin'
    - name: mysql
      run: |
        sudo service mysql stop
        apt update && apt install -y docker
        docker run --name db -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=myapp -p 3306:3306 -v $PWD/database/:/docker-entrypoint-initdb.d -d mysql:8.0.31
        sleep 30s
    # - name: buffering time for db container
    #   uses: jakejarvis/wait-action@master
    #   with:
    #     time: '30s'
    - name: test
      run: |
        export DB_HOST=0.0.0.0
        export DB_USER=root
        export DB_PASSWORD=admin
        export DB_NAME=myapp
        export SECRET_KEY="secret_key"
        python -m unittest Tests.test_auth
        python -m unittest Tests.test_app
