name: Publish

on:
  release:
    types: published

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        id: meta
        run: echo "tag=${GITHUB_REF#refs/*/v*}" >> $GITHUB_OUTPUT
      - name: trigger jenkins Job
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: "http://172.105.36.103:8080"
          jenkins_user: "abir101"
          jenkins_token: ${{ vars.JENKINS_TOKEN }}
          job_name: "publish"
          job_params: |
            {
              "TAG_NAME": "${{ steps.meta.outputs.tag }}"
            }
          job_timeout: "120"
